### ISSUE TITLE
HTTP Events are not firing on failed requests

### ISSUE THREAD

**Issue by Sammyjo20** [Sammyjo20/saloon-http-sender#4]
I'm aware of a bug with the HTTP sender where it won't fire the `RequestSending` and `ResponseReceived` Laravel events if a request fails. I wanted to put this issue here so people are aware I'm looking into it, and allow people to provide suggestions/feedback on how to fix this issue.

**Comment by ganyicz** [comment]
Hey again 😄 I think I stumbled upon a solution already, will send a PR in couple minutes
