### ISSUE TITLE
Requests not being recorded in Laravel Telescope

### ISSUE THREAD

**Issue by scajal** [Sammyjo20/saloon-http-sender#6]
I'm using the package to manage my API connections in my Laravel application.
In my development environment, Telescope is not recording any Saloon request made with this sender. 
Any ideas?

Thanks!

**Comment by Sammyjo20** [comment]
Hey @scajal! Thanks for your issue - which version of the package are you using? Make sure to upgrade to the latest v0.3.1 as we fixed a couple of issues with reporting requests in Telescope.

Also have you made sure to configure the HttpSender in either your config file or within the `resolveSender` method on your connector? 

https://docs.saloon.dev/digging-deeper/laravel-integration#configuration

**Comment by scajal** [comment]
Hi @Sammyjo20, thanks for the quick response.
I'm using version 0.3.1, and I've the config file configured as follows:

![image](https://user-images.githubusercontent.com/68784404/223879023-395d8a8d-d4ae-4233-a640-c38c2cd69ea3.png)

I had to change the namespace to `Saloon\HttpSender\HttpSender` because the namespace specified in the docs (`Saloon\HttpSender\Http\Senders\HttpSender`) didn't work for me.

**Comment by Sammyjo20** [comment]
Thank you for letting me know about the namespace in the docs - I have now updated that :) 

Are your config files cached in Laravel? Try running `php artisan config:clear` to reset any config caching that might be going on.

Are your requests being sent properly? Are there any errors with them? 

What kind of response type is it?

**Comment by scajal** [comment]
Tried reseting the cache but nothing happened.
The requests are being sent properly, yes, no errors in them. The response is always JSON.

**Comment by Sammyjo20** [comment]
The requests would be displayed under "HTTP Client" section of Passport - just checking is this where you've been looking? Also have you tried sending a request with the Laravel HTTP Client to make sure Passport is properly capturing requests?

**Comment by scajal** [comment]
Oh, my bad! I was looking under the "Requests" section of Telescope. 
I can see them under "HTTP Client".

Sorry! Thanks for the clarification.

**Comment by Sammyjo20** [comment]
Fantastic! I will update the docs accordingly. Enjoy Saloon 🤠
